name: Keep Render Flask API Warm

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes (UTC)

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Flask API to keep it alive
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://upskilme-analysis.onrender.com || echo "API Unreachable"
